name = "social-choice-theory"
version = "0.1.0"
defaultTargets = ["social-choice-theory"]

[[lean_lib]]
name = "SocialChoiceTheory"

[[lean_exe]]
name = "social-choice-theory"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "Canonical"
scope = "chasenorman"
